name: forrest_department_gr_and_updatees_app
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  google_nav_bar: ^5.0.7
  syncfusion_flutter_pdfviewer: ^29.2.11
  photo_view: ^0.15.0
  share_plus: ^11.0.0
  pdfx: ^2.9.2
  dio: ^5.8.0+1
  http: ^1.1.0
  path_provider: ^2.1.5
  provider: ^6.1.5
  file_picker: ^10.2.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/original/
    - assets/images/original/शासन निर्णय व परिपत्रके1/
    - assets/data/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans-BoldItalic.ttf
          style: italic
          weight: 700
